= Singleton Pattern

== Intent (意图)

[quote,Erich Gamma - Richard Helm - Ralph Johnson - John M. Vlissides - 1994,Design Patterns: Elements of Reusable Object-Oriented Software-addison-wesley]
Ensure a class only has one instance, and provide a global point of access to it. +
_确保一个类仅有一个实例，并提供一个访问它的全局访问点_

== Motivation (动机)

It's important for some classes to have exactly one instance.
对于一些类来说，只有一个实例是很重要的。(后面给出一些 xref:context-about-one-instance[具体案例])

How do we ensure that a class has only one instance and that the instance is easily accessible?
怎样保证一个类只有一个实例并且这个实例易于被访问？


[quote,Erich Gamma - Richard Helm - Ralph Johnson - John M. Vlissides - 1994,Design Patterns: Elements of Reusable Object-Oriented Software-addison-wesley]
*A better solution is to make the class itself responsible for keeping track of its sole instance. The class can ensure that no other instance can be created (by intercepting requests to create new objects), and it can provide a way to access the instance.* This is the Singleton pattern. +
一个更好的办法是，让类自身负责保存它的唯一实例。这个类可以保证没有其他实例可以被创建（通过截取创建新对象的请求），并且它可以 提供一个访问该实例的方法。这就是单例模式。

== Applicability (适用性)

* there must be exactly one instance of a class,and it must be accessible to clients from a well-known access point. +
当类只能有一个实例而且客户可以从一个众所周知的访问点访问它时
* when the sole instance should be extensible by subclassing, and clients should be able to use an extended instance without modifying their code. +
当这个唯一实例应该时通过子类化可扩展的，并且客户应该无需更改代码就能使用一个扩展的实例时（不理解）

== Consequence (效果)

. *Controlled access to sole instance.* 对唯一实例的受控访问
. *Reduced name space.* 缩小名空间，避免存储唯一实例的全局变量污染名空间
. *Permits refinement of operations and representation.* 允许对操作和表示的精化
. *Permits a variable number of instances.* 允许可变数目的实例
. *More flexible than class operations* 比类操作更灵活

== Implementation

使用 Singleton 模式时所需要考虑的实现问题：
. *Ensuring a unique instance* 保证一个唯一的实例
. *Subclassing the Singleton class* 创建 Singleton 类的子类


=== 饿汉式：早期实例化（Early Instantiation）


[source,java]
----

include::{docdir}/src/main/java/org/example/EarlyInstantiation.java[lines=3..]

----

<1> 唯一实例
<2> 私有构造方法，阻止在类本身以外的任何地方创建类实例
<3> 提供的全局访问点



=== 懒汉式：延迟实例化（Lazy Instantiation）


----

include::{docdir}/src/main/java/org/example/LazyInstantiation.java[lines=3..]

----

<1> 唯一实例

[source,java]

==== Double Check Lock
----

include::{docdir}/src/main/java/org/example/LazyInstantiationByDCL.java[lines=3..]

----

<1> 私有构造方法，阻止在类本身以外的任何地方创建类实例
<2> 唯一实例：等待第一次使用时再创建（延迟实例化）
<3> 提供的全局访问点
<4> 第一次检查实例：为了解决同步锁只会再第一次创建时才会使用，其余时间不再需要同步锁，减少性能的浪费
<5> 第一次创建实例时加同步锁：加锁为了解决多线程时该方法会产生多个实例
<6> 再次检查实例
<7> 对唯一实例加上 volatile 关键字：避免多线程中发生指令重排序


==== Bill pugh approach： Static Inner Helper Class

----

include::{docdir}/src/main/java/org/example/LazyInstantiationByInnerClass.java[lines=3..]

----

=== 注册式（登记式）
DCL式 和 Bill Pugh 式 都会因为反射而对单例模式造成破坏，所以使用枚举式和容器式来处理通过反序列化破坏单例模式的情况。

==== 枚举式

----

include::{docdir}/src/main/java/org/example/EnumSingleton.java[lines=3..]

----

==== 容器式

----

include::{docdir}/src/main/java/org/example/ContainerSingleton.java[lines=3..]

----


== Known Uses (已知应用)

* J2EE 中的 ServletContext 、ServletContextConfig
* Spring 中的 ApplicationContext
* 数据库连接池
* etc.

[[context-about-one-instance]]
=== 只有一个实例的场景

* Web应用中的请求执行流程场景

==== Web应用中的请求执行流程场景

== Related Patterns
Many patterns can be implemented using the Singleton pattern. See Abstract Factory, Builder, and Prototype.


== Conclusion

. 类中有且仅有一个实例并且提供一个全局访问点访问该实例，这就是单例模式
. 使用单例模式的好处多多；如节约资源、提高性能
. 常见的单例模式使用场景：J2EE 中的 ServletContext、 ServletContextConfig，Spring 中的 ApplicationContext， 数据库连接池等
. 单例模式的实现方法有很多种，推荐使用枚举式或容器式，以及 Bill Pugh 单例模式实现

== Reference

* [设计模式：可复用面向对象软件的基础]
* [HeadFirst 设计模式]
* https://juejin.cn/post/7080318543492808734[为什么要使用单例 - 掘金]
* https://www.cnblogs.com/xcgShare/p/11951891.html[]
* https://blog.csdn.net/mnb65482/article/details/80458571[深入理解单例模式]
* https://www.cnblogs.com/aaronhoo/p/7423457.html[Java 的内部类]
* https://www.cnblogs.com/dolphin0520/p/3811445.html[Java 内部类详解]
* https://blog.csdn.net/qq_28181131/article/details/82258877[Java 中静态内部类的加载时机]
* https://dzone.com/articles/singleton-bill-pugh-solution-or-enum[Singletons: Bill Pugh Solution or Enum]
* https://blog.csdn.net/qq_37960603/article/details/103944203[双重检查锁单例模式为什么要用 volatile 关键字]
